### ISSUE TITLE
Fix Spelling mistake in feature request template

### ISSUE THREAD

**Issue by janethavi** [codeJunctionTeam/codeJunction-site#33]
**Describe the bug**
Fix spelling mistake in the feature request template.
Section:- Expected Behvior
Behaviour is spelt wrong here.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to add new issue
2. Click on a feature request
3. Check "Expected Behvior" section

**Expected behavior**
That section should be corrected as Expected Behaviour.

**Comment by rishier827** [comment]
Can i get assigned

**Comment by janethavi** [comment]
Sure you can go ahead!
