### ISSUE TITLE
Remove all the unwanted components

### ISSUE THREAD

**Issue by janethavi** [codeJunctionTeam/codeJunction-site#34]
**Describe the bug**
Remove all the unwanted template components from the home page. This includes all the images which we aren't using.

**Comment by rishier827** [comment]
Can i get assigned

**Comment by janethavi** [comment]
Sure @rishier827! Go Ahead :)

**Comment by rajitha1998** [comment]
@rishier827  Have you configured the [git email](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-email-address-for-every-repository-on-your-computer) in your local machine. seems like your previous commits haven't recorded.

**Comment by rishier827** [comment]
@rajitha1998  Done thanks :)
